[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.88"
repository = "https://github.com/itshak/cbvault"

[workspace.dependencies]
gigachess = "0.1.9"
cbvault-format = { version = "0.1.0", path = "crates/cbvault-format" }
cbvault-chess = { version = "0.1.0", path = "crates/cbvault-chess" }
cbvault = { version = "0.1.0", path = "crates/cbvault" }
cbvault-fixtures = { version = "0.1.0", path = "crates/cbvault-fixtures" }
rayon = "1.10"
memmap2 = "0.9"



[workspace.lints.rust]
missing_docs = "warn"
unsafe_code = "warn"
rust_2018_idioms = "warn"

[workspace.lints.clippy]
all = "warn"
dbg_macro = "warn"
todo = "warn"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

