//! PGN output: a game's tags and its move tree as standard algebraic
//! notation.
//!
//! The writer streams: it holds one game's nodes (its moves, their SAN and the
//! shape of the tree), never a database, and a caller that reuses one
//! [`PgnWriter`] keeps those buffers from game to game. SAN is generated by
//! `gigachess` at this boundary only.
//!
//! Ported from `cbformat`'s `pgn/{mod,tree}.rs` (MIT, `oschess-cb-bridge` @
//! `ca9e8f8e`), re-based on `gigachess` (SAN from `gigachess::san`) and
//! written to a caller's sink instead of a `String`; the annotation parts of
//! the ancestor's writer come with the annotation tasks. See
//! `docs/provenance.md`.

use std::io::{self, Write};

use cbh_chess::decode::{GameRef, MoveSink, NULL_MOVE, start_as_played, walk_from};
use cbh_chess::start::{Start, start_board};
use cbh_format::cbh::{Entities, GameMoves};
use cbh_format::error::{Error, Result};
use cbh_format::game::{GameResult, Head, Player, ROUND_TEXT_BYTES, RecordKind, round_text};
use gigachess::san::move_to_san;
use gigachess::{Board, Color, Move};

/// No child of a node.
const NONE: u32 = u32::MAX;

/// One decoded move: its SAN in the shared text buffer, the move number and
/// side it was played with, and its place in the tree.
#[derive(Debug)]
struct Node {
    san: (u32, u32),
    fullmove: u16,
    white: bool,
    first_child: u32,
    last_child: u32,
    next_sibling: u32,
}

/// A game's move tree while it is decoded: the nodes, the SAN text and the
/// open brackets.
#[derive(Debug, Default)]
struct Tree {
    nodes: Vec<Node>,
    sans: String,
    cur: u32,
    parent_of_last: u32,
    branches: Vec<u32>,
}

impl Tree {
    /// An empty tree with the root node.
    fn new() -> Tree {
        Tree {
            nodes: vec![Node {
                san: (0, 0),
                fullmove: 0,
                white: true,
                first_child: NONE,
                last_child: NONE,
                next_sibling: NONE,
            }],
            ..Default::default()
        }
    }

    /// Empties the tree, keeping its buffers for the next game.
    fn clear(&mut self) {
        self.nodes.truncate(1);
        self.nodes[0].first_child = NONE;
        self.nodes[0].last_child = NONE;
        self.sans.clear();
        self.cur = 0;
        self.parent_of_last = 0;
        self.branches.clear();
    }
}

impl MoveSink for Tree {
    fn play(&mut self, before: &Board, mv: u16, _main: bool) {
        let start = self.sans.len() as u32;
        match mv {
            NULL_MOVE => self.sans.push_str("--"),
            mv => {
                let mv = Move::from_word(mv);
                match move_to_san(before, mv) {
                    Some(san) => self.sans.push_str(&san),
                    None => self.sans.push_str("??"),
                }
            }
        }
        let white = before.turn() == Color::White;
        let fullmove = before.fullmove_number();
        let id = self.nodes.len() as u32;
        self.nodes.push(Node {
            san: (start, self.sans.len() as u32),
            fullmove,
            white,
            first_child: NONE,
            last_child: NONE,
            next_sibling: NONE,
        });
        let cur = self.cur as usize;
        match self.nodes[cur].last_child {
            NONE => self.nodes[cur].first_child = id,
            last => self.nodes[last as usize].next_sibling = id,
        }
        self.nodes[cur].last_child = id;
        self.parent_of_last = self.cur;
        self.cur = id;
    }

    fn played(&mut self, _after: &Board) {}

    fn branch(&mut self) {
        self.branches.push(self.parent_of_last);
    }

    fn resume(&mut self) {
        // The walk calls `resume` only with a branch outstanding.
        self.cur = self.branches.pop().unwrap_or(0);
    }
}

/// Writes move `n`, its number when due, and says whether a comment followed
/// it (none yet: comments come with the annotation tasks).
fn write_move(out: &mut String, tree: &Tree, n: u32, force_number: bool) -> bool {
    use std::fmt::Write as _;

    let node = &tree.nodes[n as usize];
    // Writing to a String cannot fail.
    let _ = if node.white {
        write!(out, "{}. ", node.fullmove)
    } else if force_number {
        write!(out, "{}... ", node.fullmove)
    } else {
        Ok(())
    };
    let san = tree.sans.get(node.san.0 as usize..node.san.1 as usize).unwrap_or("??");
    out.push_str(san);
    out.push(' ');
    false
}

/// Writes the tree below the root as movetext, in PGN order: iterative, so a
/// deeply nested game costs heap and not stack.
fn emit(tree: &Tree, out: &mut String) {
    enum Step {
        /// Continue the line whose last written move is `node`.
        Line { node: u32, force_number: bool },
        /// Write the alternative `alt` to the main move `main`, and those after it.
        Alternatives { main: u32, alt: u32 },
        /// The alternatives end; return to the main move, repeating its number.
        Close,
    }
    let nodes = &tree.nodes;
    let mut steps = vec![Step::Line { node: 0, force_number: true }];
    while let Some(step) = steps.pop() {
        match step {
            Step::Line { node, force_number } => {
                let main = nodes[node as usize].first_child;
                if main == NONE {
                    continue;
                }
                let commented = write_move(out, tree, main, force_number);
                match nodes[main as usize].next_sibling {
                    NONE => steps.push(Step::Line { node: main, force_number: commented }),
                    alt => steps.push(Step::Alternatives { main, alt }),
                }
            }
            Step::Alternatives { main, alt } => {
                if alt == NONE {
                    // Back on the main line after its alternatives: repeat the number.
                    steps.push(Step::Line { node: main, force_number: true });
                } else {
                    steps.push(Step::Alternatives { main, alt: nodes[alt as usize].next_sibling });
                    steps.push(Step::Close);
                    out.push('(');
                    let commented = write_move(out, tree, alt, true);
                    steps.push(Step::Line { node: alt, force_number: commented });
                }
            }
            Step::Close => {
                if out.ends_with(' ') {
                    out.pop();
                }
                out.push_str(") ");
            }
        }
    }
}

/// The tag roster of a game: its tournament, players, date, result and start.
fn write_tags<H: Head>(out: &mut String, header: &H, entities: &Entities, start: &Start, board: &Board) -> Result<()> {
    use std::fmt::Write as _;

    let id = |v: i64| -> Option<u32> { (v >= 0).then_some(v as u32) };
    let tournament = match id(header.tournament()) {
        Some(id) => entities.tournament(id)?.unwrap_or_default(),
        None => Default::default(),
    };
    let player = |v: i64| -> Result<Option<Player>> {
        Ok(match id(v) {
            Some(id) => entities.player(id)?,
            None => None,
        })
    };
    let title = if tournament.title.is_empty() { "?".to_string() } else { tournament.title.clone() };
    let place = if tournament.place.is_empty() { "?".to_string() } else { tournament.place.clone() };
    let mut round_buf = [0u8; ROUND_TEXT_BYTES];
    let (round, sub) = header.round();
    let round = round_tag(round, sub, &mut round_buf);

    let _ = writeln!(out, r#"[Event "{}"]"#, escape(&title));
    let _ = writeln!(out, r#"[Site "{}"]"#, escape(&place));
    let _ = writeln!(out, r#"[Date "{}"]"#, header.played_date().pgn());
    let _ = writeln!(out, r#"[Round "{}"]"#, if round.is_empty() { "?" } else { &round });
    let _ = writeln!(out, r#"[White "{}"]"#, escape(&player_name(player(header.white())?)));
    let _ = writeln!(out, r#"[Black "{}"]"#, escape(&player_name(player(header.black())?)));
    let _ = writeln!(out, r#"[Result "{}"]"#, result_tag(header.result()));
    if let Some(eco) = header.eco().pgn() {
        let _ = writeln!(out, r#"[ECO "{eco}"]"#);
    }
    let (white_elo, black_elo) = header.elo();
    if white_elo > 0 {
        let _ = writeln!(out, r#"[WhiteElo "{white_elo}"]"#);
    }
    if black_elo > 0 {
        let _ = writeln!(out, r#"[BlackElo "{black_elo}"]"#);
    }
    if *start != Start::Standard {
        if matches!(start, Start::Chess960(_)) || matches!(start, Start::Setup(s) if s.chess960) {
            let _ = writeln!(out, r#"[Variant "Chess960"]"#);
        }
        let _ = writeln!(out, r#"[SetUp "1"]"#);
        let _ = writeln!(out, r#"[FEN "{}"]"#, board.to_fen());
    }
    out.push('\n');
    Ok(())
}

/// The text of a PGN tag value: a quote or a backslash is escaped, and
/// ChessBase's figurine codes are written as letters. `None` becomes `?`.
fn escape(text: &str) -> String {
    let has_figurine = text.chars().any(|c| figurine(c).is_some());
    if !text.contains(['"', '\\']) && !has_figurine {
        return text.to_owned();
    }
    let mut out = String::with_capacity(text.len() + 2);
    for c in text.chars() {
        if let Some(letter) = figurine(c) {
            out.push(letter);
            continue;
        }
        if c == '"' || c == '\\' {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

/// The letter of a ChessBase figurine code, if `c` is one. The tournament
/// titles that record piece odds carry the codes `U+E025`…`U+E029` for
/// queen, rook, bishop, knight and pawn — `Odds <Q>d1`, `Odds <R>a1+ <N>b1`
/// — and ChessBase's own PGN export writes them as the letters. `U+E024`
/// completes the sequence for a king; no title in the local database uses it.
fn figurine(c: char) -> Option<char> {
    match c {
        '\u{e024}' => Some('K'),
        '\u{e025}' => Some('Q'),
        '\u{e026}' => Some('R'),
        '\u{e027}' => Some('B'),
        '\u{e028}' => Some('N'),
        '\u{e029}' => Some('P'),
        _ => None,
    }
}

/// A player as ChessBase's export writes the name: `Last, First`, with a
/// period after a first name that is only initials — one or two letters/digits
/// (e.g. `Delaire, H.`, `Ward, JH.`, or disambiguated historical players
/// like `Johnston, A1.`) — and longer first names as stored. `?` when the
/// record has no name.
fn player_name(player: Option<Player>) -> String {
    let Some(player) = player else { return "?".to_owned() };
    if player.first.is_empty() {
        return if player.last.is_empty() { "?".to_owned() } else { player.last };
    }
    let initials = (1..=2).contains(&player.first.len())
        && player.first.bytes().all(|b| b.is_ascii_uppercase() || b.is_ascii_digit());
    format!("{}, {}{}", player.last, player.first, if initials { "." } else { "" })
}

/// A round and sub-round as ChessBase's export writes them: `5`, `5.2` for
/// the second game of round 5, or `?.4` when only the sub-round is known.
fn round_tag(round: i32, sub: i32, buf: &mut [u8; ROUND_TEXT_BYTES]) -> String {
    if round <= 0 && sub > 0 {
        return format!("?.{sub}");
    }
    let text = round_text(round, sub, buf);
    match (text.find('('), text.find(')')) {
        (Some(open), Some(close)) => format!("{}.{}", &text[..open], &text[open + 1..close]),
        _ => text.to_owned(),
    }
}

/// The result as ChessBase's export writes it: `*` where the record has
/// result 7 (both players lost); `0-0` is no PGN result token.
pub fn result_tag(result: GameResult) -> &'static str {
    match result {
        GameResult::BothLost => "*",
        other => other.pgn(),
    }
}

/// A game's decode error as an I/O error carrying it.
fn as_io(e: Error) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, e)
}

/// Writes PGN into a caller's sink, reusing its buffers from game to game.
#[derive(Debug, Default)]
pub struct PgnWriter {
    tree: Tree,
    tags: String,
    movetext: String,
}

impl PgnWriter {
    /// A writer with empty buffers.
    pub fn new() -> PgnWriter {
        PgnWriter { tree: Tree::new(), tags: String::new(), movetext: String::new() }
    }

    /// The bytes the writer keeps for reuse (its high-water mark): a caller
    /// exporting many games holds one game's worth, not a database's.
    pub fn capacity(&self) -> usize {
        self.tags.capacity()
            + self.movetext.capacity()
            + self.tree.sans.capacity()
            + self.tree.nodes.capacity() * size_of::<Node>()
    }

    /// Writes game `game` of `header` as PGN: the tags, the movetext with its
    /// variations, and the result. Entities come from `entities`; the game
    /// must be a game (not a guiding text).
    pub fn write_game<H: Head>(
        &mut self,
        out: &mut impl Write,
        header: &H,
        entities: &Entities,
        game: &GameMoves<'_>,
    ) -> io::Result<()> {
        if header.kind() != RecordKind::Game {
            return Err(io::Error::new(io::ErrorKind::InvalidData, format!("record {} is not a game", header.id())));
        }
        let what = GameRef::new(header.id());
        let start = start_as_played(what, game).map_err(as_io)?;
        let board = start_board(&start).map_err(as_io)?;
        self.tree.clear();
        self.tags.clear();
        self.movetext.clear();
        write_tags(&mut self.tags, header, entities, &start, &board).map_err(as_io)?;
        walk_from(what, game, &start, &mut self.tree).map_err(as_io)?;
        emit(&self.tree, &mut self.movetext);
        out.write_all(self.tags.as_bytes())?;
        out.write_all(self.movetext.as_bytes())?;
        out.write_all(result_tag(header.result()).as_bytes())?;
        out.write_all(b"\n\n")
    }
}
