//! Synthetic 2CBH fixtures for the tests, built from the layout in
//! `docs/format-spec-2cbh.md` rather than from any real database.
//!
//! The local ChessBase sets are copyrighted and are **not** in this repository,
//! and neither is anything derived from their bytes. Every byte a test here
//! reads is therefore generated by the functions below from the *verified
//! layout* — the frame arithmetic, the little-endian fields, the
//! `88 77 66 55 44 33 22 11` magic and the `ff ff` terminator are the format's,
//! not a copy of anyone's game, name or commentary. A test that needs a real
//! set is gated on `CBVAULT_TEST_2CBH` and says loudly that it did not run.

use std::path::{Path, PathBuf};

use super::bytes::{CONTENT_OFFSET, FILE_HEADER_SIZE, FIXED_OVERHEAD, RECORD_MAGIC, RECORD_SIZE, TERMINATOR_SIZE};

/// A 12-byte `.2cbg`/`.2cba` file header for a file of `size` bytes, with the
/// first record at [`FILE_HEADER_SIZE`].
pub fn file_header(size: u64) -> [u8; FILE_HEADER_SIZE] {
    let mut h = [0u8; FILE_HEADER_SIZE];
    h[0..8].copy_from_slice(&size.to_le_bytes());
    h[8..10].copy_from_slice(&(FILE_HEADER_SIZE as u16).to_le_bytes());
    h
}

/// A whole record: the magic, `a` and `b`, the 8-byte tag, `content`, the
/// `ff ff` terminator, zero padding and the length trailer. Every arithmetic
/// rule of spec §5 is applied here, so a fixture that round-trips through
/// [`crate::twocbh::Record::parse`] is a fixture the format allows.
///
/// `a` is taken from the content length, so a caller passes the bytes it wants
/// and the frame is built around them.
pub fn record(b: u32, content: &[u8]) -> Vec<u8> {
    record_with(content.len() as u32, b, content)
}

/// The same as [`record`], with `a` stated explicitly — for a test that
/// corrupts a length field and needs the stated value not to be recomputed.
pub fn record_with(a: u32, b: u32, content: &[u8]) -> Vec<u8> {
    assert_eq!(
        CONTENT_OFFSET + a as usize + TERMINATOR_SIZE + b as usize + 8,
        FIXED_OVERHEAD + a as usize + b as usize
    );
    let total = FIXED_OVERHEAD + a as usize + b as usize;
    let mut r = Vec::with_capacity(total);
    r.extend_from_slice(&RECORD_MAGIC);
    r.extend_from_slice(&a.to_le_bytes());
    r.extend_from_slice(&b.to_le_bytes());
    r.extend_from_slice(&[0xa5; 8]); // the per-record word: distinct in the wild
    r.extend_from_slice(content);
    r.extend_from_slice(&[0xff, 0xff]);
    r.resize(total, 0);
    let n = r.len();
    r[n - 8..].copy_from_slice(&(n as u64).to_le_bytes());
    r
}

/// A `.2cbg`/`.2cba` file of the given records, with the header's size field
/// filled in to match.
pub fn segment(records: &[Vec<u8>]) -> Vec<u8> {
    let body: usize = records.iter().map(|r| r.len()).sum();
    let size = (FILE_HEADER_SIZE + body) as u64;
    let mut out = file_header(size).to_vec();
    for r in records {
        out.extend_from_slice(r);
    }
    out
}

/// A 192-byte `.2cbh` record. `moves` and `annotations` are the two offsets
/// the format's whole reader rests on; `kind` is the kind byte.
pub fn header_record(kind: u8, moves: u64, annotations: u64, names: (&[u8], &[u8])) -> [u8; RECORD_SIZE] {
    let mut b = [0u8; RECORD_SIZE];
    b[0] = kind;
    b[0x01] = 0x00;
    b[0x02] = 0x01;
    b[0x03] = 0x01;
    b[0x08..0x10].copy_from_slice(&moves.to_le_bytes());
    b[0x10..0x18].copy_from_slice(&annotations.to_le_bytes());
    b[0x40..0x50].fill(0xff);
    let n1 = names.0.len().min(16);
    b[0x68..0x68 + n1].copy_from_slice(&names.0[..n1]);
    let n2 = names.1.len().min(16);
    b[0x78..0x78 + n2].copy_from_slice(&names.1[..n2]);
    b[0xb8..0xbc].copy_from_slice(&1u32.to_le_bytes());
    b
}

/// A whole `.2cbh` file: its own header record (stating the count and the
/// record size) followed by `games`.
///
/// The count field is the **total** number of 192-byte records, the file's own
/// included — verified against every local set (a 21,143,232-byte file states
/// 110,121 = size/192) — so it is one more than the number of games.
pub fn headers(games: &[[u8; RECORD_SIZE]], generation: u8) -> Vec<u8> {
    let mut out = vec![0u8; RECORD_SIZE];
    out[0x08] = generation;
    out[0x0a..0x0c].copy_from_slice(&(RECORD_SIZE as u16).to_le_bytes());
    out[0x10..0x14].copy_from_slice(&((games.len() + 1) as u32).to_le_bytes());
    for g in games {
        out.extend_from_slice(g);
    }
    out
}

/// One synthetic game: its kind byte, its per-game key, and its two names.
#[derive(Clone, Copy)]
pub struct Game {
    /// The record's kind byte (`0x01` for a game).
    pub kind: u8,
    /// The value stored at `0x98`, distinct per game as in the real sets.
    pub key: u64,
    /// The two inline name fields.
    pub names: (&'static [u8], &'static [u8]),
}

impl Game {
    /// A game with the given key and two names.
    pub fn new(key: u64, one: &'static [u8], two: &'static [u8]) -> Game {
        Game { kind: 1, key, names: (one, two) }
    }
}

/// Writes a synthetic 2CBH set of `games` into a uniquely named directory
/// under the temp dir and returns its base path, laid out as the real sets
/// are: `.2cbh`, and `.2cbg`/`.2cba` each a 12-byte header then records.
///
/// With `annotations` false no `.2cba` is written, which is the one member a
/// caller can legitimately find missing.
pub fn write_set(tag: &str, games: &[Game], annotations: bool) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("cbvault-twocbh-{}-{tag}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("the fixture directory");
    let stem = dir.join("fixture");

    let mut heads: Vec<[u8; RECORD_SIZE]> = Vec::new();
    let mut moves: Vec<Vec<u8>> = Vec::new();
    let mut notes: Vec<Vec<u8>> = Vec::new();
    for g in games {
        let m = record(102, &[0x5a; 28]);
        let mo = (FILE_HEADER_SIZE + moves.iter().map(|r| r.len()).sum::<usize>()) as u64;
        let ao = if annotations {
            let a = record(198, &[0u8; 24]);
            let at = (FILE_HEADER_SIZE + notes.iter().map(|r| r.len()).sum::<usize>()) as u64;
            notes.push(a);
            at
        } else {
            0
        };
        let mut h = header_record(g.kind, mo, ao, g.names);
        h[0x98..0xa0].copy_from_slice(&g.key.to_le_bytes());
        heads.push(h);
        moves.push(m);
    }
    std::fs::write(format!("{}.2cbh", stem.display()), headers(&heads, 0x22)).expect("write .2cbh");
    std::fs::write(format!("{}.2cbg", stem.display()), segment(&moves)).expect("write .2cbg");
    if annotations {
        std::fs::write(format!("{}.2cba", stem.display()), segment(&notes)).expect("write .2cba");
    }
    stem
}

/// Removes a set written by [`write_set`].
pub fn remove_set(stem: &Path) {
    if let Some(dir) = stem.parent() {
        let _ = std::fs::remove_dir_all(dir);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_written_set_has_the_count_its_header_states() {
        let games = [Game::new(1, b"a", b"b"), Game::new(2, b"c", b"d")];
        let stem = write_set("count", &games, true);
        let bytes = std::fs::read(format!("{}.2cbh", stem.display())).unwrap();
        assert_eq!(bytes.len() / RECORD_SIZE, 3, "the file's own record plus two games");
        assert_eq!(u32::from_le_bytes(bytes[0x10..0x14].try_into().unwrap()), 3);
        remove_set(&stem);
    }
}
